version: "3.9"

services:
  backend:
    build: ./habit_tracker
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=habit_tracker.settings
      - PYTHONUNBUFFERED=1
    volumes:
      - ./habit_tracker:/app
    networks:
      - habits-network
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./habit_tracker_fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./habit_tracker_fe:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - habits-network

networks:
  habits-network:
    driver: bridge
